apiVersion: v1
kind: Service
metadata:
  name: express-ts-svc
spec:
  selector:
    app: express-ts-label
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30390
