apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odl-netconf-pvc
  namespace: default
spec:
  accessModes:
      - "ReadWriteOnce"
  selector:
    matchLabels:
      name: odl-netconf-pv
  resources:
      requests:
          storage: "5Gi"
  storageClassName: odl
