apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /tmp/conf
      name: empty-volume
  volumes:
  - name: empty-volume
    emptyDir: {}