kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: pv-test
  resources:
    requests:
      storage: 1Gi